name: robomimic

services:
  robomimic:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
        PYTORCH_WHEEL_URL: ${PYTORCH_WHEEL_URL:-https://mirrors.aliyun.com/pytorch-wheels/cu128}
        UBUNTU_APT_MIRROR: ${UBUNTU_APT_MIRROR:-https://mirrors.tuna.tsinghua.edu.cn/ubuntu}
    image: robomimic:latest
    gpus: all
    shm_size: 2gb
    environment:
      DISPLAY: ${DISPLAY:-}
      XAUTHORITY: /tmp/.docker.xauth
      MUJOCO_GL: glfw
      NVIDIA_DRIVER_CAPABILITIES: all
      ZSH_CACHE_DIR: /tmp/oh-my-zsh-cache
      HF_HOME: /opt/models/huggingface
      HF_ENDPOINT: ${HF_ENDPOINT:-https://hf-mirror.com}
    volumes:
      - type: bind
        source: .
        target: /opt/robomimic
      - type: bind
        source: ./datasets
        target: /opt/robomimic/datasets
        bind:
          create_host_path: true
      - type: bind
        source: ./outputs
        target: /opt/robomimic/outputs
        bind:
          create_host_path: true
      - type: bind
        source: ./models/huggingface
        target: /opt/models/huggingface
        bind:
          create_host_path: true
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${XAUTHORITY:-/dev/null}
        target: /tmp/.docker.xauth
        read_only: true
        bind:
          create_host_path: false
      - type: bind
        source: ${HOME:-/root}/.oh-my-zsh
        target: /root/.oh-my-zsh
        read_only: true
        bind:
          create_host_path: false
    working_dir: /opt/robomimic
    stdin_open: true
    tty: true
    command: ["/usr/bin/zsh", "-l"]
